export const EMPLOYEES_LIST_REQUEST = 'EMPLOYEES_LIST_REQUEST';
export const EMPLOYEES_LIST_SUCCESS = 'EMPLOYEES_LIST_SUCCESS';
export const EMPLOYEES_LIST_FAIL = 'EMPLOYEES_LIST_FAIL';

export const UPDATE_EMPLOYEES_CHECK_BOX = 'UPDATE_EMPLOYEES_CHECK_BOX';

export const EMPLOYEE_ADD = 'EMPLOYEE_ADD';
export const EMPLOYEE_REMOVE = 'EMPLOYEE_REMOVE';
